apiVersion: v1
kind: Secret
metadata:
  name: kube-bind-backend-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: kube-bind-backend
type: kubernetes.io/service-account-token
