apiVersion: v2
name: kube-bind-portal
description: Kube Bind Portal - Angular UI for kube-bind provider
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: common
    version: 0.12.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
